'use strict';

const USER_ROLE_KEYS = [
  'PRIMARY_USERNAME',
  'CONTACT_FRIEND_USERNAME',
  'CONTACT_NON_FRIEND_USERNAME',
  'CONTACT_EXISTING_FRIEND_USERNAME',
  'CONTACT_FRIEND_TO_ADD_USERNAME',
  'CONTACT_INVITATION_SMOKE_USERNAME',
  'CHAT_PEER_USERNAME',
  'GROUP_OWNER_USERNAME',
  'GROUP_MEMBER_USERNAME_1',
  'GROUP_MEMBER_USERNAME_2',
  'GROUP_NON_MEMBER_USERNAME_1',
  'GROUP_NON_MEMBER_USERNAME_2',
  'ROOM_OWNER_USERNAME',
  'ROOM_MEMBER_USERNAME_1',
  'ROOM_MEMBER_USERNAME_2',
  'ROOM_NON_MEMBER_USERNAME_1',
  'ROOM_NON_MEMBER_USERNAME_2',
];

const CONTACT_CANDIDATE_KEYS = [
  'CONTACT_FRIEND_USERNAME',
  'CONTACT_NON_FRIEND_USERNAME',
  'CONTACT_EXISTING_FRIEND_USERNAME',
  'CONTACT_FRIEND_TO_ADD_USERNAME',
  'CONTACT_INVITATION_SMOKE_USERNAME',
];

const TARGET_FRIEND_KEYS = [
  'CONTACT_FRIEND_USERNAME',
  'CONTACT_EXISTING_FRIEND_USERNAME',
];

const RECIPROCAL_FRIEND_KEYS = [
  'CONTACT_FRIEND_USERNAME',
];

function buildFixtureUsers(userPrefix, defaultPassword) {
  const users = {};
  USER_ROLE_KEYS.forEach((roleKey, index) => {
    users[roleKey] = `${userPrefix}_${String(index + 1).padStart(3, '0')}`;
  });
  users.PRIMARY_PASSWORD = defaultPassword;
  return users;
}

function getAllUsernames(users) {
  return USER_ROLE_KEYS.map((roleKey) => users[roleKey]);
}

function buildAccountEnv({ appKey, userPrefix, defaultPassword, users }) {
  return {
    APP_KEY: appKey,
    USER_PREFIX: userPrefix,
    DEFAULT_PASSWORD: defaultPassword,
    PRIMARY_USERNAME: users.PRIMARY_USERNAME,
    PRIMARY_PASSWORD: defaultPassword,
    CONTACT_FRIEND_USERNAME: users.CONTACT_FRIEND_USERNAME,
    CONTACT_NON_FRIEND_USERNAME: users.CONTACT_NON_FRIEND_USERNAME,
    CONTACT_EXISTING_FRIEND_USERNAME: users.CONTACT_EXISTING_FRIEND_USERNAME,
    CONTACT_FRIEND_TO_ADD_USERNAME: users.CONTACT_FRIEND_TO_ADD_USERNAME,
    CONTACT_INVITATION_SMOKE_USERNAME: users.CONTACT_INVITATION_SMOKE_USERNAME,
    CHAT_PEER_USERNAME: users.CHAT_PEER_USERNAME,
    GROUP_OWNER_USERNAME: users.GROUP_OWNER_USERNAME,
    GROUP_MEMBER_USERNAME_1: users.GROUP_MEMBER_USERNAME_1,
    GROUP_MEMBER_USERNAME_2: users.GROUP_MEMBER_USERNAME_2,
    GROUP_NON_MEMBER_USERNAME_1: users.GROUP_NON_MEMBER_USERNAME_1,
    GROUP_NON_MEMBER_USERNAME_2: users.GROUP_NON_MEMBER_USERNAME_2,
    ROOM_OWNER_USERNAME: users.ROOM_OWNER_USERNAME,
    ROOM_MEMBER_USERNAME_1: users.ROOM_MEMBER_USERNAME_1,
    ROOM_MEMBER_USERNAME_2: users.ROOM_MEMBER_USERNAME_2,
    ROOM_NON_MEMBER_USERNAME_1: users.ROOM_NON_MEMBER_USERNAME_1,
    ROOM_NON_MEMBER_USERNAME_2: users.ROOM_NON_MEMBER_USERNAME_2,
  };
}

module.exports = {
  CONTACT_CANDIDATE_KEYS,
  RECIPROCAL_FRIEND_KEYS,
  TARGET_FRIEND_KEYS,
  USER_ROLE_KEYS,
  buildAccountEnv,
  buildFixtureUsers,
  getAllUsernames,
};
