// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatGroupManager} from '../biz/BizChatGroupManager';

export const dispatchChatGroupManagerCommands = new Set<string>([
  'getGroupWithId',
  'getJoinedGroups',
  'fetchJoinedGroupsFromServer',
  'fetchPublicGroupsFromServer',
  'createGroupEx',
  'fetchGroupInfoWithoutMembersFromServer',
  'fetchMemberListFromServer',
  'fetchMemberInfoListFromServer',
  'fetchBlockListFromServer',
  'fetchMuteListFromServer',
  'fetchAllowListFromServer',
  'isMemberInAllowListFromServer',
  'fetchGroupFileListFromServer',
  'fetchAnnouncementFromServer',
  'addMembers',
  'inviteUser',
  'removeMembers',
  'blockMembers',
  'unblockMembers',
  'changeGroupName',
  'changeGroupDescription',
  'leaveGroup',
  'destroyGroup',
  'blockGroup',
  'unblockGroup',
  'changeOwner',
  'addAdmin',
  'removeAdmin',
  'muteMembers',
  'unMuteMembers',
  'muteAllMembers',
  'unMuteAllMembers',
  'addAllowList',
  'removeAllowList',
  'uploadGroupSharedFile',
  'downloadGroupSharedFile',
  'removeGroupSharedFile',
  'updateGroupAnnouncement',
  'updateGroupAvatar',
  'updateGroupExtension',
  'joinPublicGroup',
  'requestToJoinPublicGroup',
  'acceptJoinApplication',
  'declineJoinApplication',
  'acceptInvitation',
  'declineInvitation',
  'setMemberAttribute',
  'fetchMemberAttributes',
  'fetchMembersAttributes',
  'fetchJoinedGroupCount',
]);

export function dispatchChatGroupManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'getGroupWithId':
      BizChatGroupManager.getGroupWithId(info, callback);
      return true;
    case 'getJoinedGroups':
      BizChatGroupManager.getJoinedGroups(info, callback);
      return true;
    case 'fetchJoinedGroupsFromServer':
      BizChatGroupManager.fetchJoinedGroupsFromServer(info, callback);
      return true;
    case 'fetchPublicGroupsFromServer':
      BizChatGroupManager.fetchPublicGroupsFromServer(info, callback);
      return true;
    case 'createGroupEx':
      BizChatGroupManager.createGroupEx(info, callback);
      return true;
    case 'fetchGroupInfoWithoutMembersFromServer':
      BizChatGroupManager.fetchGroupInfoWithoutMembersFromServer(info, callback);
      return true;
    case 'fetchMemberListFromServer':
      BizChatGroupManager.fetchMemberListFromServer(info, callback);
      return true;
    case 'fetchMemberInfoListFromServer':
      BizChatGroupManager.fetchMemberInfoListFromServer(info, callback);
      return true;
    case 'fetchBlockListFromServer':
      BizChatGroupManager.fetchBlockListFromServer(info, callback);
      return true;
    case 'fetchMuteListFromServer':
      BizChatGroupManager.fetchMuteListFromServer(info, callback);
      return true;
    case 'fetchAllowListFromServer':
      BizChatGroupManager.fetchAllowListFromServer(info, callback);
      return true;
    case 'isMemberInAllowListFromServer':
      BizChatGroupManager.isMemberInAllowListFromServer(info, callback);
      return true;
    case 'fetchGroupFileListFromServer':
      BizChatGroupManager.fetchGroupFileListFromServer(info, callback);
      return true;
    case 'fetchAnnouncementFromServer':
      BizChatGroupManager.fetchAnnouncementFromServer(info, callback);
      return true;
    case 'addMembers':
      BizChatGroupManager.addMembers(info, callback);
      return true;
    case 'inviteUser':
      BizChatGroupManager.inviteUser(info, callback);
      return true;
    case 'removeMembers':
      BizChatGroupManager.removeMembers(info, callback);
      return true;
    case 'blockMembers':
      BizChatGroupManager.blockMembers(info, callback);
      return true;
    case 'unblockMembers':
      BizChatGroupManager.unblockMembers(info, callback);
      return true;
    case 'changeGroupName':
      BizChatGroupManager.changeGroupName(info, callback);
      return true;
    case 'changeGroupDescription':
      BizChatGroupManager.changeGroupDescription(info, callback);
      return true;
    case 'leaveGroup':
      BizChatGroupManager.leaveGroup(info, callback);
      return true;
    case 'destroyGroup':
      BizChatGroupManager.destroyGroup(info, callback);
      return true;
    case 'blockGroup':
      BizChatGroupManager.blockGroup(info, callback);
      return true;
    case 'unblockGroup':
      BizChatGroupManager.unblockGroup(info, callback);
      return true;
    case 'changeOwner':
      BizChatGroupManager.changeOwner(info, callback);
      return true;
    case 'addAdmin':
      BizChatGroupManager.addAdmin(info, callback);
      return true;
    case 'removeAdmin':
      BizChatGroupManager.removeAdmin(info, callback);
      return true;
    case 'muteMembers':
      BizChatGroupManager.muteMembers(info, callback);
      return true;
    case 'unMuteMembers':
      BizChatGroupManager.unMuteMembers(info, callback);
      return true;
    case 'muteAllMembers':
      BizChatGroupManager.muteAllMembers(info, callback);
      return true;
    case 'unMuteAllMembers':
      BizChatGroupManager.unMuteAllMembers(info, callback);
      return true;
    case 'addAllowList':
      BizChatGroupManager.addAllowList(info, callback);
      return true;
    case 'removeAllowList':
      BizChatGroupManager.removeAllowList(info, callback);
      return true;
    case 'uploadGroupSharedFile':
      BizChatGroupManager.uploadGroupSharedFile(info, callback);
      return true;
    case 'downloadGroupSharedFile':
      BizChatGroupManager.downloadGroupSharedFile(info, callback);
      return true;
    case 'removeGroupSharedFile':
      BizChatGroupManager.removeGroupSharedFile(info, callback);
      return true;
    case 'updateGroupAnnouncement':
      BizChatGroupManager.updateGroupAnnouncement(info, callback);
      return true;
    case 'updateGroupAvatar':
      BizChatGroupManager.updateGroupAvatar(info, callback);
      return true;
    case 'updateGroupExtension':
      BizChatGroupManager.updateGroupExtension(info, callback);
      return true;
    case 'joinPublicGroup':
      BizChatGroupManager.joinPublicGroup(info, callback);
      return true;
    case 'requestToJoinPublicGroup':
      BizChatGroupManager.requestToJoinPublicGroup(info, callback);
      return true;
    case 'acceptJoinApplication':
      BizChatGroupManager.acceptJoinApplication(info, callback);
      return true;
    case 'declineJoinApplication':
      BizChatGroupManager.declineJoinApplication(info, callback);
      return true;
    case 'acceptInvitation':
      BizChatGroupManager.acceptInvitation(info, callback);
      return true;
    case 'declineInvitation':
      BizChatGroupManager.declineInvitation(info, callback);
      return true;
    case 'setMemberAttribute':
      BizChatGroupManager.setMemberAttribute(info, callback);
      return true;
    case 'fetchMemberAttributes':
      BizChatGroupManager.fetchMemberAttributes(info, callback);
      return true;
    case 'fetchMembersAttributes':
      BizChatGroupManager.fetchMembersAttributes(info, callback);
      return true;
    case 'fetchJoinedGroupCount':
      BizChatGroupManager.fetchJoinedGroupCount(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`BizChatGroupManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
