// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatManager} from '../biz/BizChatManager';

export function dispatchChatManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'sendMessage':
      BizChatManager.sendMessage(info, callback);
      return true;
    case 'resendMessage':
      BizChatManager.resendMessage(info, callback);
      return true;
    case 'sendMessageReadAck':
      BizChatManager.sendMessageReadAck(info, callback);
      return true;
    case 'sendConversationReadAck':
      BizChatManager.sendConversationReadAck(info, callback);
      return true;
    case 'recallMessage':
      BizChatManager.recallMessage(info, callback);
      return true;
    case 'getMessagesWithIds':
      BizChatManager.getMessagesWithIds(info, callback);
      return true;
    case 'markAllConversationsAsRead':
      BizChatManager.markAllConversationsAsRead(info, callback);
      return true;
    case 'insertMessage':
      BizChatManager.insertMessage(info, callback);
      return true;
    case 'updateMessage':
      BizChatManager.updateMessage(info, callback);
      return true;
    case 'importMessages':
      BizChatManager.importMessages(info, callback);
      return true;
    case 'downloadAttachmentInCombine':
      BizChatManager.downloadAttachmentInCombine(info, callback);
      return true;
    case 'downloadThumbnailInCombine':
      BizChatManager.downloadThumbnailInCombine(info, callback);
      return true;
    case 'downloadAttachment':
      BizChatManager.downloadAttachment(info, callback);
      return true;
    case 'downloadThumbnail':
      BizChatManager.downloadThumbnail(info, callback);
      return true;
    case 'fetchHistoryMessagesByOptions':
      BizChatManager.fetchHistoryMessagesByOptions(info, callback);
      return true;
    case 'getMsgsWithKeyword':
      BizChatManager.getMsgsWithKeyword(info, callback);
      return true;
    case 'getConvsMsgsWithKeyword':
      BizChatManager.getConvsMsgsWithKeyword(info, callback);
      return true;
    case 'getConversation':
      BizChatManager.getConversation(info, callback);
      return true;
    case 'deleteConversation':
      BizChatManager.deleteConversation(info, callback);
      return true;
    case 'markMessageAsRead':
      BizChatManager.markMessageAsRead(info, callback);
      return true;
    case 'deleteMessage':
      BizChatManager.deleteMessage(info, callback);
      return true;
    case 'translateMessage':
      BizChatManager.translateMessage(info, callback);
      return true;
    case 'addReaction':
      BizChatManager.addReaction(info, callback);
      return true;
    case 'removeReaction':
      BizChatManager.removeReaction(info, callback);
      return true;
    case 'fetchReactionList':
      BizChatManager.fetchReactionList(info, callback);
      return true;
    case 'fetchReactionDetail':
      BizChatManager.fetchReactionDetail(info, callback);
      return true;
    case 'reportMessage':
      BizChatManager.reportMessage(info, callback);
      return true;
    case 'getReactionList':
      BizChatManager.getReactionList(info, callback);
      return true;
    case 'groupAckCount':
      BizChatManager.groupAckCount(info, callback);
      return true;
    case 'getMessageThread':
      BizChatManager.getMessageThread(info, callback);
      return true;
    case 'getThreadConversation':
      BizChatManager.getThreadConversation(info, callback);
      return true;
    case 'removeMessagesFromServerWithMsgIds':
      BizChatManager.removeMessagesFromServerWithMsgIds(info, callback);
      return true;
    case 'removeMessagesFromServerWithTimestamp':
      BizChatManager.removeMessagesFromServerWithTimestamp(info, callback);
      return true;
    case 'fetchConversationsFromServerWithCursor':
      BizChatManager.fetchConversationsFromServerWithCursor(info, callback);
      return true;
    case 'fetchPinnedConversationsFromServerWithCursor':
      BizChatManager.fetchPinnedConversationsFromServerWithCursor(info, callback);
      return true;
    case 'pinConversation':
      BizChatManager.pinConversation(info, callback);
      return true;
    case 'modifyMsgBody':
      BizChatManager.modifyMsgBody(info, callback);
      return true;
    case 'fetchCombineMessageDetail':
      BizChatManager.fetchCombineMessageDetail(info, callback);
      return true;
    case 'addRemoteAndLocalConversationsMark':
      BizChatManager.addRemoteAndLocalConversationsMark(info, callback);
      return true;
    case 'deleteRemoteAndLocalConversationsMark':
      BizChatManager.deleteRemoteAndLocalConversationsMark(info, callback);
      return true;
    case 'fetchConversationsByOptions':
      BizChatManager.fetchConversationsByOptions(info, callback);
      return true;
    case 'deleteAllMessageAndConversation':
      BizChatManager.deleteAllMessageAndConversation(info, callback);
      return true;
    case 'pinMessage':
      BizChatManager.pinMessage(info, callback);
      return true;
    case 'unpinMessage':
      BizChatManager.unpinMessage(info, callback);
      return true;
    case 'fetchPinnedMessages':
      BizChatManager.fetchPinnedMessages(info, callback);
      return true;
    case 'getPinnedMessages':
      BizChatManager.getPinnedMessages(info, callback);
      return true;
    case 'getMessagePinInfo':
      BizChatManager.getMessagePinInfo(info, callback);
      return true;
    case 'getMessageCountWithTimestamp':
      BizChatManager.getMessageCountWithTimestamp(info, callback);
      return true;
    case 'getMessageCount':
      BizChatManager.getMessageCount(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`BizChatManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
