// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatPushManager} from '../biz/BizChatPushManager';

export function dispatchChatPushManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatPushManager.setSilentModeForConversation':
      BizChatPushManager.setSilentModeForConversation(info, callback);
      return true;
    case 'ChatPushManager.removeSilentModeForConversation':
      BizChatPushManager.removeSilentModeForConversation(info, callback);
      return true;
    case 'ChatPushManager.fetchSilentModeForConversation':
      BizChatPushManager.fetchSilentModeForConversation(info, callback);
      return true;
    case 'ChatPushManager.setSilentModeForAll':
      BizChatPushManager.setSilentModeForAll(info, callback);
      return true;
    case 'ChatPushManager.fetchSilentModeForAll':
      BizChatPushManager.fetchSilentModeForAll(info, callback);
      return true;
    case 'ChatPushManager.fetchSilentModeForConversations':
      BizChatPushManager.fetchSilentModeForConversations(info, callback);
      return true;
    case 'ChatPushManager.setPreferredNotificationLanguage':
      BizChatPushManager.setPreferredNotificationLanguage(info, callback);
      return true;
    case 'ChatPushManager.fetchPreferredNotificationLanguage':
      BizChatPushManager.fetchPreferredNotificationLanguage(info, callback);
      return true;
    case 'ChatPushManager.updatePushNickname':
      BizChatPushManager.updatePushNickname(info, callback);
      return true;
    case 'ChatPushManager.updatePushDisplayStyle':
      BizChatPushManager.updatePushDisplayStyle(info, callback);
      return true;
    case 'ChatPushManager.fetchPushOptionFromServer':
      BizChatPushManager.fetchPushOptionFromServer(info, callback);
      return true;
    case 'ChatPushManager.selectPushTemplate':
      BizChatPushManager.selectPushTemplate(info, callback);
      return true;
    case 'ChatPushManager.fetchSelectedPushTemplate':
      BizChatPushManager.fetchSelectedPushTemplate(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatPushManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
