// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatRoomManager} from '../biz/BizChatRoomManager';

export function dispatchChatRoomManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatRoomManager.joinChatRoomEx':
      BizChatRoomManager.joinChatRoomEx(info, callback);
      return true;
    case 'ChatRoomManager.leaveChatRoom':
      BizChatRoomManager.leaveChatRoom(info, callback);
      return true;
    case 'ChatRoomManager.fetchPublicChatRoomsFromServer':
      BizChatRoomManager.fetchPublicChatRoomsFromServer(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomInfoFromServer':
      BizChatRoomManager.fetchChatRoomInfoFromServer(info, callback);
      return true;
    case 'ChatRoomManager.getChatRoomWithId':
      BizChatRoomManager.getChatRoomWithId(info, callback);
      return true;
    case 'ChatRoomManager.createChatRoom':
      BizChatRoomManager.createChatRoom(info, callback);
      return true;
    case 'ChatRoomManager.destroyChatRoom':
      BizChatRoomManager.destroyChatRoom(info, callback);
      return true;
    case 'ChatRoomManager.changeChatRoomSubject':
      BizChatRoomManager.changeChatRoomSubject(info, callback);
      return true;
    case 'ChatRoomManager.changeChatRoomDescription':
      BizChatRoomManager.changeChatRoomDescription(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomMembers':
      BizChatRoomManager.fetchChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.muteChatRoomMembers':
      BizChatRoomManager.muteChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.unMuteChatRoomMembers':
      BizChatRoomManager.unMuteChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.changeOwner':
      BizChatRoomManager.changeOwner(info, callback);
      return true;
    case 'ChatRoomManager.addChatRoomAdmin':
      BizChatRoomManager.addChatRoomAdmin(info, callback);
      return true;
    case 'ChatRoomManager.removeChatRoomAdmin':
      BizChatRoomManager.removeChatRoomAdmin(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomMuteList':
      BizChatRoomManager.fetchChatRoomMuteList(info, callback);
      return true;
    case 'ChatRoomManager.removeChatRoomMembers':
      BizChatRoomManager.removeChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.blockChatRoomMembers':
      BizChatRoomManager.blockChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.unBlockChatRoomMembers':
      BizChatRoomManager.unBlockChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomBlockList':
      BizChatRoomManager.fetchChatRoomBlockList(info, callback);
      return true;
    case 'ChatRoomManager.updateChatRoomAnnouncement':
      BizChatRoomManager.updateChatRoomAnnouncement(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomAnnouncement':
      BizChatRoomManager.fetchChatRoomAnnouncement(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomAllowListFromServer':
      BizChatRoomManager.fetchChatRoomAllowListFromServer(info, callback);
      return true;
    case 'ChatRoomManager.isMemberInChatRoomAllowList':
      BizChatRoomManager.isMemberInChatRoomAllowList(info, callback);
      return true;
    case 'ChatRoomManager.isMemberInChatRoomMuteList':
      BizChatRoomManager.isMemberInChatRoomMuteList(info, callback);
      return true;
    case 'ChatRoomManager.addMembersToChatRoomAllowList':
      BizChatRoomManager.addMembersToChatRoomAllowList(info, callback);
      return true;
    case 'ChatRoomManager.removeMembersFromChatRoomAllowList':
      BizChatRoomManager.removeMembersFromChatRoomAllowList(info, callback);
      return true;
    case 'ChatRoomManager.muteAllChatRoomMembers':
      BizChatRoomManager.muteAllChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.unMuteAllChatRoomMembers':
      BizChatRoomManager.unMuteAllChatRoomMembers(info, callback);
      return true;
    case 'ChatRoomManager.fetchChatRoomAttributes':
      BizChatRoomManager.fetchChatRoomAttributes(info, callback);
      return true;
    case 'ChatRoomManager.addAttributes':
      BizChatRoomManager.addAttributes(info, callback);
      return true;
    case 'ChatRoomManager.removeAttributes':
      BizChatRoomManager.removeAttributes(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatRoomManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
