// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {BizChatRoomManager} from '../biz/BizChatRoomManager';

export function dispatchChatRoomManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
): boolean {
  switch (cmd) {
    case 'joinChatRoomEx':
      BizChatRoomManager.joinChatRoomEx(info, callback);
      return true;
    case 'fetchChatRoomInfoFromServer':
      BizChatRoomManager.fetchChatRoomInfoFromServer(info, callback);
      return true;
    case 'getChatRoomWithId':
      BizChatRoomManager.getChatRoomWithId(info, callback);
      return true;
    case 'fetchChatRoomAllowListFromServer':
      BizChatRoomManager.fetchChatRoomAllowListFromServer(info, callback);
      return true;
    case 'isMemberInChatRoomAllowList':
      BizChatRoomManager.isMemberInChatRoomAllowList(info, callback);
      return true;
    case 'isMemberInChatRoomMuteList':
      BizChatRoomManager.isMemberInChatRoomMuteList(info, callback);
      return true;
    case 'addMembersToChatRoomAllowList':
      BizChatRoomManager.addMembersToChatRoomAllowList(info, callback);
      return true;
    case 'removeMembersFromChatRoomAllowList':
      BizChatRoomManager.removeMembersFromChatRoomAllowList(info, callback);
      return true;
    case 'muteAllChatRoomMembers':
      BizChatRoomManager.muteAllChatRoomMembers(info, callback);
      return true;
    case 'unMuteAllChatRoomMembers':
      BizChatRoomManager.unMuteAllChatRoomMembers(info, callback);
      return true;
    case 'fetchChatRoomAttributes':
      BizChatRoomManager.fetchChatRoomAttributes(info, callback);
      return true;
    default:
      return false;
  }
}
