// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {BizChatPushManager} from '../biz/BizChatPushManager';

export function dispatchChatPushManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
): boolean {
  switch (cmd) {
    case 'setSilentModeForConversation':
      BizChatPushManager.setSilentModeForConversation(info, callback);
      return true;
    case 'removeSilentModeForConversation':
      BizChatPushManager.removeSilentModeForConversation(info, callback);
      return true;
    case 'fetchSilentModeForConversation':
      BizChatPushManager.fetchSilentModeForConversation(info, callback);
      return true;
    case 'setSilentModeForAll':
      BizChatPushManager.setSilentModeForAll(info, callback);
      return true;
    case 'fetchSilentModeForAll':
      BizChatPushManager.fetchSilentModeForAll(info, callback);
      return true;
    case 'fetchSilentModeForConversations':
      BizChatPushManager.fetchSilentModeForConversations(info, callback);
      return true;
    case 'setPreferredNotificationLanguage':
      BizChatPushManager.setPreferredNotificationLanguage(info, callback);
      return true;
    case 'selectPushTemplate':
      BizChatPushManager.selectPushTemplate(info, callback);
      return true;
    case 'fetchSelectedPushTemplate':
      BizChatPushManager.fetchSelectedPushTemplate(info, callback);
      return true;
    default:
      return false;
  }
}
