// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatUserInfoManager} from '../biz/BizChatUserInfoManager';

export function dispatchChatUserInfoManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatUserInfoManager.updateOwnUserInfo':
      BizChatUserInfoManager.updateOwnUserInfo(info, callback);
      return true;
    case 'ChatUserInfoManager.fetchUserInfoById':
      BizChatUserInfoManager.fetchUserInfoById(info, callback);
      return true;
    case 'ChatUserInfoManager.fetchOwnInfo':
      BizChatUserInfoManager.fetchOwnInfo(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatUserInfoManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
