// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {BizChatUserInfoManager} from '../biz/BizChatUserInfoManager';

export function dispatchChatUserInfoManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
): boolean {
  switch (cmd) {
    case 'fetchOwnInfo':
      BizChatUserInfoManager.fetchOwnInfo(info, callback);
      return true;
    default:
      return false;
  }
}
