// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatClient} from '../biz/BizChatClient';

export function dispatchChatClient(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'isConnected':
      BizChatClient.isConnected(info, callback);
      return true;
    case 'getCurrentUsername':
      BizChatClient.getCurrentUsername(info, callback);
      return true;
    case 'isLoginBefore':
      BizChatClient.isLoginBefore(info, callback);
      return true;
    case 'getAccessToken':
      BizChatClient.getAccessToken(info, callback);
      return true;
    case 'createAccount':
      BizChatClient.createAccount(info, callback);
      return true;
    case 'loginWithToken':
      BizChatClient.loginWithToken(info, callback);
      return true;
    case 'renewAgoraToken':
      BizChatClient.renewAgoraToken(info, callback);
      return true;
    case 'logout':
      BizChatClient.logout(info, callback);
      return true;
    case 'changeAppKey':
      BizChatClient.changeAppKey(info, callback);
      return true;
    case 'changeAppId':
      BizChatClient.changeAppId(info, callback);
      return true;
    case 'compressLogs':
      BizChatClient.compressLogs(info, callback);
      return true;
    case 'getLoggedInDevicesFromServer':
      BizChatClient.getLoggedInDevicesFromServer(info, callback);
      return true;
    case 'kickDevice':
      BizChatClient.kickDevice(info, callback);
      return true;
    case 'kickAllDevices':
      BizChatClient.kickAllDevices(info, callback);
      return true;
    case 'updatePushConfig':
      BizChatClient.updatePushConfig(info, callback);
      return true;
    case 'getRTCTokenInfoWithChannelName':
      BizChatClient.getRTCTokenInfoWithChannelName(info, callback);
      return true;
    case 'getUserIdsWithRTCUids':
      BizChatClient.getUserIdsWithRTCUids(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`BizChatClient: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
