// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatContactManager} from '../biz/BizChatContactManager';

export function dispatchChatContactManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatContactManager.addContact':
      BizChatContactManager.addContact(info, callback);
      return true;
    case 'ChatContactManager.deleteContact':
      BizChatContactManager.deleteContact(info, callback);
      return true;
    case 'ChatContactManager.getAllContactsFromServer':
      BizChatContactManager.getAllContactsFromServer(info, callback);
      return true;
    case 'ChatContactManager.getAllContactsFromDB':
      BizChatContactManager.getAllContactsFromDB(info, callback);
      return true;
    case 'ChatContactManager.addUserToBlockList':
      BizChatContactManager.addUserToBlockList(info, callback);
      return true;
    case 'ChatContactManager.removeUserFromBlockList':
      BizChatContactManager.removeUserFromBlockList(info, callback);
      return true;
    case 'ChatContactManager.getBlockListFromServer':
      BizChatContactManager.getBlockListFromServer(info, callback);
      return true;
    case 'ChatContactManager.getBlockListFromDB':
      BizChatContactManager.getBlockListFromDB(info, callback);
      return true;
    case 'ChatContactManager.acceptInvitation':
      BizChatContactManager.acceptInvitation(info, callback);
      return true;
    case 'ChatContactManager.declineInvitation':
      BizChatContactManager.declineInvitation(info, callback);
      return true;
    case 'ChatContactManager.getSelfIdsOnOtherPlatform':
      BizChatContactManager.getSelfIdsOnOtherPlatform(info, callback);
      return true;
    case 'ChatContactManager.getAllContacts':
      BizChatContactManager.getAllContacts(info, callback);
      return true;
    case 'ChatContactManager.getContact':
      BizChatContactManager.getContact(info, callback);
      return true;
    case 'ChatContactManager.fetchAllContacts':
      BizChatContactManager.fetchAllContacts(info, callback);
      return true;
    case 'ChatContactManager.fetchContacts':
      BizChatContactManager.fetchContacts(info, callback);
      return true;
    case 'ChatContactManager.setContactRemark':
      BizChatContactManager.setContactRemark(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatContactManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
