// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {BizChatPresenceManager} from '../biz/BizChatPresenceManager';

export function dispatchChatPresenceManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
): boolean {
  switch (cmd) {
    case 'publishPresence':
      BizChatPresenceManager.publishPresence(info, callback);
      return true;
    case 'fetchSubscribedMembers':
      BizChatPresenceManager.fetchSubscribedMembers(info, callback);
      return true;
    case 'fetchPresenceStatus':
      BizChatPresenceManager.fetchPresenceStatus(info, callback);
      return true;
    default:
      return false;
  }
}
