// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatPresenceManager} from '../biz/BizChatPresenceManager';

export function dispatchChatPresenceManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatPresenceManager.publishPresence':
      BizChatPresenceManager.publishPresence(info, callback);
      return true;
    case 'ChatPresenceManager.subscribe':
      BizChatPresenceManager.subscribe(info, callback);
      return true;
    case 'ChatPresenceManager.unsubscribe':
      BizChatPresenceManager.unsubscribe(info, callback);
      return true;
    case 'ChatPresenceManager.fetchSubscribedMembers':
      BizChatPresenceManager.fetchSubscribedMembers(info, callback);
      return true;
    case 'ChatPresenceManager.fetchPresenceStatus':
      BizChatPresenceManager.fetchPresenceStatus(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatPresenceManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
