// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {BizChatGroupManager} from '../biz/BizChatGroupManager';

export function dispatchChatGroupManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
): boolean {
  switch (cmd) {
    case 'getGroupWithId':
      BizChatGroupManager.getGroupWithId(info, callback);
      return true;
    case 'getJoinedGroups':
      BizChatGroupManager.getJoinedGroups(info, callback);
      return true;
    case 'fetchJoinedGroupsFromServer':
      BizChatGroupManager.fetchJoinedGroupsFromServer(info, callback);
      return true;
    case 'fetchPublicGroupsFromServer':
      BizChatGroupManager.fetchPublicGroupsFromServer(info, callback);
      return true;
    case 'createGroupEx':
      BizChatGroupManager.createGroupEx(info, callback);
      return true;
    case 'fetchGroupInfoWithoutMembersFromServer':
      BizChatGroupManager.fetchGroupInfoWithoutMembersFromServer(info, callback);
      return true;
    case 'fetchMemberInfoListFromServer':
      BizChatGroupManager.fetchMemberInfoListFromServer(info, callback);
      return true;
    case 'inviteUser':
      BizChatGroupManager.inviteUser(info, callback);
      return true;
    case 'changeGroupName':
      BizChatGroupManager.changeGroupName(info, callback);
      return true;
    case 'changeGroupDescription':
      BizChatGroupManager.changeGroupDescription(info, callback);
      return true;
    case 'leaveGroup':
      BizChatGroupManager.leaveGroup(info, callback);
      return true;
    case 'destroyGroup':
      BizChatGroupManager.destroyGroup(info, callback);
      return true;
    case 'blockGroup':
      BizChatGroupManager.blockGroup(info, callback);
      return true;
    case 'uploadGroupSharedFile':
      BizChatGroupManager.uploadGroupSharedFile(info, callback);
      return true;
    case 'downloadGroupSharedFile':
      BizChatGroupManager.downloadGroupSharedFile(info, callback);
      return true;
    case 'updateGroupAnnouncement':
      BizChatGroupManager.updateGroupAnnouncement(info, callback);
      return true;
    case 'updateGroupAvatar':
      BizChatGroupManager.updateGroupAvatar(info, callback);
      return true;
    case 'joinPublicGroup':
      BizChatGroupManager.joinPublicGroup(info, callback);
      return true;
    case 'setMemberAttribute':
      BizChatGroupManager.setMemberAttribute(info, callback);
      return true;
    case 'fetchMemberAttributes':
      BizChatGroupManager.fetchMemberAttributes(info, callback);
      return true;
    case 'fetchMembersAttributes':
      BizChatGroupManager.fetchMembersAttributes(info, callback);
      return true;
    case 'fetchJoinedGroupCount':
      BizChatGroupManager.fetchJoinedGroupCount(info, callback);
      return true;
    default:
      return false;
  }
}
