// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatGroupManager} from '../biz/BizChatGroupManager';

export function dispatchChatGroupManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatGroupManager.getGroupWithId':
      BizChatGroupManager.getGroupWithId(info, callback);
      return true;
    case 'ChatGroupManager.getJoinedGroups':
      BizChatGroupManager.getJoinedGroups(info, callback);
      return true;
    case 'ChatGroupManager.fetchJoinedGroupsFromServer':
      BizChatGroupManager.fetchJoinedGroupsFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchPublicGroupsFromServer':
      BizChatGroupManager.fetchPublicGroupsFromServer(info, callback);
      return true;
    case 'ChatGroupManager.createGroupEx':
      BizChatGroupManager.createGroupEx(info, callback);
      return true;
    case 'ChatGroupManager.fetchGroupInfoWithoutMembersFromServer':
      BizChatGroupManager.fetchGroupInfoWithoutMembersFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchMemberListFromServer':
      BizChatGroupManager.fetchMemberListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchMemberInfoListFromServer':
      BizChatGroupManager.fetchMemberInfoListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchBlockListFromServer':
      BizChatGroupManager.fetchBlockListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchMuteListFromServer':
      BizChatGroupManager.fetchMuteListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchAllowListFromServer':
      BizChatGroupManager.fetchAllowListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.isMemberInAllowListFromServer':
      BizChatGroupManager.isMemberInAllowListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchGroupFileListFromServer':
      BizChatGroupManager.fetchGroupFileListFromServer(info, callback);
      return true;
    case 'ChatGroupManager.fetchAnnouncementFromServer':
      BizChatGroupManager.fetchAnnouncementFromServer(info, callback);
      return true;
    case 'ChatGroupManager.addMembers':
      BizChatGroupManager.addMembers(info, callback);
      return true;
    case 'ChatGroupManager.inviteUser':
      BizChatGroupManager.inviteUser(info, callback);
      return true;
    case 'ChatGroupManager.removeMembers':
      BizChatGroupManager.removeMembers(info, callback);
      return true;
    case 'ChatGroupManager.blockMembers':
      BizChatGroupManager.blockMembers(info, callback);
      return true;
    case 'ChatGroupManager.unblockMembers':
      BizChatGroupManager.unblockMembers(info, callback);
      return true;
    case 'ChatGroupManager.changeGroupName':
      BizChatGroupManager.changeGroupName(info, callback);
      return true;
    case 'ChatGroupManager.changeGroupDescription':
      BizChatGroupManager.changeGroupDescription(info, callback);
      return true;
    case 'ChatGroupManager.leaveGroup':
      BizChatGroupManager.leaveGroup(info, callback);
      return true;
    case 'ChatGroupManager.destroyGroup':
      BizChatGroupManager.destroyGroup(info, callback);
      return true;
    case 'ChatGroupManager.blockGroup':
      BizChatGroupManager.blockGroup(info, callback);
      return true;
    case 'ChatGroupManager.unblockGroup':
      BizChatGroupManager.unblockGroup(info, callback);
      return true;
    case 'ChatGroupManager.changeOwner':
      BizChatGroupManager.changeOwner(info, callback);
      return true;
    case 'ChatGroupManager.addAdmin':
      BizChatGroupManager.addAdmin(info, callback);
      return true;
    case 'ChatGroupManager.removeAdmin':
      BizChatGroupManager.removeAdmin(info, callback);
      return true;
    case 'ChatGroupManager.muteMembers':
      BizChatGroupManager.muteMembers(info, callback);
      return true;
    case 'ChatGroupManager.unMuteMembers':
      BizChatGroupManager.unMuteMembers(info, callback);
      return true;
    case 'ChatGroupManager.muteAllMembers':
      BizChatGroupManager.muteAllMembers(info, callback);
      return true;
    case 'ChatGroupManager.unMuteAllMembers':
      BizChatGroupManager.unMuteAllMembers(info, callback);
      return true;
    case 'ChatGroupManager.addAllowList':
      BizChatGroupManager.addAllowList(info, callback);
      return true;
    case 'ChatGroupManager.removeAllowList':
      BizChatGroupManager.removeAllowList(info, callback);
      return true;
    case 'ChatGroupManager.uploadGroupSharedFile':
      BizChatGroupManager.uploadGroupSharedFile(info, callback);
      return true;
    case 'ChatGroupManager.downloadGroupSharedFile':
      BizChatGroupManager.downloadGroupSharedFile(info, callback);
      return true;
    case 'ChatGroupManager.removeGroupSharedFile':
      BizChatGroupManager.removeGroupSharedFile(info, callback);
      return true;
    case 'ChatGroupManager.updateGroupAnnouncement':
      BizChatGroupManager.updateGroupAnnouncement(info, callback);
      return true;
    case 'ChatGroupManager.updateGroupAvatar':
      BizChatGroupManager.updateGroupAvatar(info, callback);
      return true;
    case 'ChatGroupManager.updateGroupExtension':
      BizChatGroupManager.updateGroupExtension(info, callback);
      return true;
    case 'ChatGroupManager.joinPublicGroup':
      BizChatGroupManager.joinPublicGroup(info, callback);
      return true;
    case 'ChatGroupManager.requestToJoinPublicGroup':
      BizChatGroupManager.requestToJoinPublicGroup(info, callback);
      return true;
    case 'ChatGroupManager.acceptJoinApplication':
      BizChatGroupManager.acceptJoinApplication(info, callback);
      return true;
    case 'ChatGroupManager.declineJoinApplication':
      BizChatGroupManager.declineJoinApplication(info, callback);
      return true;
    case 'ChatGroupManager.acceptInvitation':
      BizChatGroupManager.acceptInvitation(info, callback);
      return true;
    case 'ChatGroupManager.declineInvitation':
      BizChatGroupManager.declineInvitation(info, callback);
      return true;
    case 'ChatGroupManager.setMemberAttribute':
      BizChatGroupManager.setMemberAttribute(info, callback);
      return true;
    case 'ChatGroupManager.fetchMemberAttributes':
      BizChatGroupManager.fetchMemberAttributes(info, callback);
      return true;
    case 'ChatGroupManager.fetchMembersAttributes':
      BizChatGroupManager.fetchMembersAttributes(info, callback);
      return true;
    case 'ChatGroupManager.fetchJoinedGroupCount':
      BizChatGroupManager.fetchJoinedGroupCount(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatGroupManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
