// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatPushManager} from '../biz/BizChatPushManager';

export const dispatchChatPushManagerCommands = new Set<string>([
  'setSilentModeForConversation',
  'removeSilentModeForConversation',
  'fetchSilentModeForConversation',
  'setSilentModeForAll',
  'fetchSilentModeForAll',
  'fetchSilentModeForConversations',
  'setPreferredNotificationLanguage',
  'fetchPreferredNotificationLanguage',
  'updatePushNickname',
  'updatePushDisplayStyle',
  'fetchPushOptionFromServer',
  'selectPushTemplate',
  'fetchSelectedPushTemplate',
]);

export function dispatchChatPushManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'setSilentModeForConversation':
      BizChatPushManager.setSilentModeForConversation(info, callback);
      return true;
    case 'removeSilentModeForConversation':
      BizChatPushManager.removeSilentModeForConversation(info, callback);
      return true;
    case 'fetchSilentModeForConversation':
      BizChatPushManager.fetchSilentModeForConversation(info, callback);
      return true;
    case 'setSilentModeForAll':
      BizChatPushManager.setSilentModeForAll(info, callback);
      return true;
    case 'fetchSilentModeForAll':
      BizChatPushManager.fetchSilentModeForAll(info, callback);
      return true;
    case 'fetchSilentModeForConversations':
      BizChatPushManager.fetchSilentModeForConversations(info, callback);
      return true;
    case 'setPreferredNotificationLanguage':
      BizChatPushManager.setPreferredNotificationLanguage(info, callback);
      return true;
    case 'fetchPreferredNotificationLanguage':
      BizChatPushManager.fetchPreferredNotificationLanguage(info, callback);
      return true;
    case 'updatePushNickname':
      BizChatPushManager.updatePushNickname(info, callback);
      return true;
    case 'updatePushDisplayStyle':
      BizChatPushManager.updatePushDisplayStyle(info, callback);
      return true;
    case 'fetchPushOptionFromServer':
      BizChatPushManager.fetchPushOptionFromServer(info, callback);
      return true;
    case 'selectPushTemplate':
      BizChatPushManager.selectPushTemplate(info, callback);
      return true;
    case 'fetchSelectedPushTemplate':
      BizChatPushManager.fetchSelectedPushTemplate(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`BizChatPushManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
