// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatContactManager} from '../biz/BizChatContactManager';

export const dispatchChatContactManagerCommands = new Set<string>([
  'addContact',
  'deleteContact',
  'getAllContactsFromServer',
  'getAllContactsFromDB',
  'addUserToBlockList',
  'removeUserFromBlockList',
  'getBlockListFromServer',
  'getBlockListFromDB',
  'acceptInvitation',
  'declineInvitation',
  'getSelfIdsOnOtherPlatform',
  'getAllContacts',
  'getContact',
  'fetchAllContacts',
  'fetchContacts',
  'setContactRemark',
]);

export function dispatchChatContactManager(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'addContact':
      BizChatContactManager.addContact(info, callback);
      return true;
    case 'deleteContact':
      BizChatContactManager.deleteContact(info, callback);
      return true;
    case 'getAllContactsFromServer':
      BizChatContactManager.getAllContactsFromServer(info, callback);
      return true;
    case 'getAllContactsFromDB':
      BizChatContactManager.getAllContactsFromDB(info, callback);
      return true;
    case 'addUserToBlockList':
      BizChatContactManager.addUserToBlockList(info, callback);
      return true;
    case 'removeUserFromBlockList':
      BizChatContactManager.removeUserFromBlockList(info, callback);
      return true;
    case 'getBlockListFromServer':
      BizChatContactManager.getBlockListFromServer(info, callback);
      return true;
    case 'getBlockListFromDB':
      BizChatContactManager.getBlockListFromDB(info, callback);
      return true;
    case 'acceptInvitation':
      BizChatContactManager.acceptInvitation(info, callback);
      return true;
    case 'declineInvitation':
      BizChatContactManager.declineInvitation(info, callback);
      return true;
    case 'getSelfIdsOnOtherPlatform':
      BizChatContactManager.getSelfIdsOnOtherPlatform(info, callback);
      return true;
    case 'getAllContacts':
      BizChatContactManager.getAllContacts(info, callback);
      return true;
    case 'getContact':
      BizChatContactManager.getContact(info, callback);
      return true;
    case 'fetchAllContacts':
      BizChatContactManager.fetchAllContacts(info, callback);
      return true;
    case 'fetchContacts':
      BizChatContactManager.fetchContacts(info, callback);
      return true;
    case 'setContactRemark':
      BizChatContactManager.setContactRemark(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`BizChatContactManager: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
