// Generated by scripts/generate-dispatch-routes.js.
// Review generated diffs before committing.

import {ReturnCallback} from '../RNWS';
import {Logger} from '../Logger';
import {BizChatClient} from '../biz/BizChatClient';

export function dispatchChatClient(
  cmd: string,
  info: any,
  callback: ReturnCallback,
  logUnknown = true,
): boolean {
  switch (cmd) {
    case 'ChatClient.isConnected':
      BizChatClient.isConnected(info, callback);
      return true;
    case 'ChatClient.getCurrentUsername':
      BizChatClient.getCurrentUsername(info, callback);
      return true;
    case 'ChatClient.isLoginBefore':
      BizChatClient.isLoginBefore(info, callback);
      return true;
    case 'ChatClient.getAccessToken':
      BizChatClient.getAccessToken(info, callback);
      return true;
    case 'ChatClient.createAccount':
      BizChatClient.createAccount(info, callback);
      return true;
    case 'ChatClient.loginWithToken':
      BizChatClient.loginWithToken(info, callback);
      return true;
    case 'ChatClient.renewAgoraToken':
      BizChatClient.renewAgoraToken(info, callback);
      return true;
    case 'ChatClient.logout':
      BizChatClient.logout(info, callback);
      return true;
    case 'ChatClient.changeAppKey':
      BizChatClient.changeAppKey(info, callback);
      return true;
    case 'ChatClient.changeAppId':
      BizChatClient.changeAppId(info, callback);
      return true;
    case 'ChatClient.compressLogs':
      BizChatClient.compressLogs(info, callback);
      return true;
    case 'ChatClient.getLoggedInDevicesFromServer':
      BizChatClient.getLoggedInDevicesFromServer(info, callback);
      return true;
    case 'ChatClient.kickDevice':
      BizChatClient.kickDevice(info, callback);
      return true;
    case 'ChatClient.kickAllDevices':
      BizChatClient.kickAllDevices(info, callback);
      return true;
    case 'ChatClient.updatePushConfig':
      BizChatClient.updatePushConfig(info, callback);
      return true;
    case 'ChatClient.getRTCTokenInfoWithChannelName':
      BizChatClient.getRTCTokenInfoWithChannelName(info, callback);
      return true;
    case 'ChatClient.getUserIdsWithRTCUids':
      BizChatClient.getUserIdsWithRTCUids(info, callback);
      return true;
    default:
      if (logUnknown) {
        Logger.raw.warn(`ChatClient: unknown cmd: ${cmd}`);
      }
      return false;
  }
}
